### ISSUE TITLE
Add newCodeplug action to dmrRadio to create new empty rdt

### ISSUE THREAD

**Issue by tylert** [DaleFarnsworth-DMR/dmrRadio#1]
This is a new feature request.

It would be very useful to be able to automate the generation of brand new empty codeplug rdt files using the dmrRadio command-line tool.  Perhaps something like ```dmrRadio newCodeplug -model <model> -freq <freqRange> <codeplugFile>```.

My use-case for this new feature would be to create a new empty codeplug suitable for passing on to dmrRadio's "codeplugToJSON" action to obtain a JSON file which may then be further modified using jq and Python.

I have created a quick-and-dirty Python script to import CHIRP CSV files and spit them out as channels as an alternative to manual data entry (https://github.com/tylert/freq-lists/blob/master/codeplugs/chirp_channels.py).  I use this to build up new, modularized codeplugs for specific users/tasks.

**Comment by tylert** [comment]
@DaleFarnsworth

**Comment by DaleFarnsworth** [comment]
Resolved with commit 75aa70790024e97bc454f23e1d4b5fd7d3379d4e in v1.0.23.  Thanks!
